apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: server
  namespace: zabbix
spec:
  minReplicas: 1
  maxReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: server
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 90