apiVersion: v1
kind: Service
metadata:
  name: server-receiver-agent
  namespace: "zabbix"
spec:
  type: LoadBalancer
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 10051
      targetPort: 10051