apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: http-redirect-https
  namespace: zabbix
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT