apiVersion: v1
kind: Service
metadata:
  name: agent
  namespace: "zabbix"
spec:
  type: ClusterIP
  selector:
    app: agent
  ports:
    - name: agent
      port: 10050
      targetPort: 10050
      protocol: TCP